version: "3.8"
services:
  backend:
    container_name: dlc-webui-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ${DLC_PROJECTS}:/projects
    restart: unless-stopped

  frontend:
    container_name: dlc-webui-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
