# https://taskfile.dev

version: "3"

vars:
  CONDA_ENV: dlc-webui

tasks:
  backend:
    desc: "Run the backend"
    ignore_error: true
    deps: [is-conda-env]
    cmds:
      - uvicorn backend.main:app --reload

  frontend:
    desc: "Run the frontend"
    ignore_error: true
    dir: ./frontend
    cmds:
      - npm run dev -s -- --clearScreen false

  fullstack:
    desc: "Run the frontend and backend concurrently"
    deps: [backend, frontend]

  setup-conda:
    desc: "Setup/update the conda environment"
    deps: [has-conda]
    vars:
      envs:
        sh: conda env list
    cmds:
      - |
        {{- if (contains .CONDA_ENV .envs) -}}
          conda env update -f ./backend/conda.yaml --prune
        {{- else -}}
          conda env create -f ./backend/conda.yaml
        {{- end -}}

  dlc-gui:
    desc: "Open the DeepLabCut GUI"
    deps: [is-conda-env]
    cmds:
      - ipython -c "from deeplabcut import launch_dlc; launch_dlc()"
    ignore_error: true

  ### utility tasks ###
  has-conda:
    preconditions:
      - sh: command -v conda
        msg: conda not installed

  is-conda-env:
    deps: [has-conda]
    preconditions:
      - sh: '[[ "$CONDA_DEFAULT_ENV" == "{{.CONDA_ENV}}" ]]'
        msg: no conda environment found, try running "conda activate {{.CONDA_ENV}}"
