# https://taskfile.dev

version: "3"

vars:
  CONDA_ENV: dlc-webui

tasks:
  ### BACKEND ###
  backend:
    desc: "Run the backend"
    ignore_error: true
    deps: [is-conda-env]
    cmds:
      - uvicorn backend.app.main:app --reload

  backend:format:
    desc: Format backend code
    ignore_error: true
    preconditions:
      - sh: command -v black
        msg: black does not appear to be installed, try running "pip install black"
    cmds:
      - black ./backend {{.args}}

  backend:format:check:
    desc: Check format of the backend code
    cmds:
      - task: backend:format
        vars:
          args: --check --diff --color

  ### FRONTEND ###
  frontend:
    desc: "Run the frontend"
    ignore_error: true
    dir: ./frontend
    cmds:
      - npm run dev -s -- --clearScreen false

  frontend:lint:
    desc: "Format and lint the frontend code"
    dir: ./frontend
    cmds:
      - npm run lint:fix
      - npm run format

  frontend:lint:check:
    desc: "Check the quality of the frontend code"
    dir: ./frontend
    cmds:
      - npm run lint
      - npm run format:check

  ### SETUP ###
  setup:
    desc: "Setup the frontend and backend environments/dependencies"
    cmds:
      - task: setup-conda
      - task: setup-node

  setup-node:
    desc: "Setup pnpm and install frontend dependencies"
    dir: ./frontend
    preconditions:
      - sh: command -v node
        msg: node not installed
    cmds:
      - pnpm install

  setup-conda:
    desc: "Setup/update the conda environment"
    deps: [has-conda]
    vars:
      envs:
        sh: conda env list
    cmds:
      - |
        {{- if (contains .CONDA_ENV .envs) -}}
          conda env update -f ./backend/conda.yaml --prune
        {{- else -}}
          conda env create -f ./backend/conda.yaml
        {{- end -}}

  ### MISC ###
  fullstack:
    desc: "Run the frontend and backend concurrently"
    deps: [backend, frontend]

  lint:
    desc: "Lint and format the frontend and backend code"
    cmds:
      - task: backend:format
      - task: frontend:lint

  lint:check:
    desc: "Check the quality of the frontend and backend code"
    cmds:
      - task: backend:format:check
      - task: frontend:lint:check

  clean:
    desc: "Remove temporary files and directories"
    cmds:
      - python ./scripts/clean_backend.py
      - cd frontend && npm run clean -s

  dlc-gui:
    desc: "Open DeepLabCut's builtin GUI"
    deps: [is-conda-env]
    cmds:
      - ipython -c "from deeplabcut import launch_dlc; launch_dlc()"
    ignore_error: true

  ### UTILITIES ###
  has-conda:
    preconditions:
      - sh: command -v conda
        msg: conda not installed

  is-conda-env:
    deps: [has-conda]
    preconditions:
      - sh: '[[ "$CONDA_DEFAULT_ENV" == "{{.CONDA_ENV}}" ]]'
        msg: no conda environment found, try running "conda activate {{.CONDA_ENV}}"
